
#+BEGIN_OPTIONS
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in,top=.75in,bottom=.75in}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{color}
#+LATEX_HEADER:\usepackage[numbers,super,sort&compress]{natbib}
#+LATEX_HEADER:\usepackage{caption}
#+LATEX_HEADER:\usepackage{subcaption}
#+LATEX_HEADER:\captionsetup{font=footnotesize}
#+LATEX_HEADER:\usepackage[version=3]{mhchem}
#+LATEX_HEADER:\usepackage{siunitx}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{paralist}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{enumitem}
#+LATEX_HEADER:\usepackage{mdwlist}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\usepackage{wrapfig}
#+LATEX_HEADER:\usepackage{nopageno}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\fancyhead[LE,RO]{\scriptsize Jerry Crum}
#+LATEX_HEADER:\fancyhead[RE,LO]{\scriptsize ZSE Outline}
#+LATEX_HEADER:%\fancyfoot[CE,CO]{\leftmark}
#+LATEX_HEADER:\fancyfoot[LE,RO]{\thepage}
#+LATEX_HEADER:%\usepackage{subfig}
#+LATEX_HEADER:\usepackage{comment}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[section]{placeins}
#+LATEX_HEADER: \usepackage{siunitx}

#+LATEX_HEADER:\DeclareGraphicsExtensions{.pdf,.png,.jpg}
#+LATEX_HEADER:\newcommand{\red}[1]{\textcolor{red}{#1}}
#+LATEX_HEADER:\newcommand{\blue}[1]{\textcolor{blue}{#1}}
#+LATEX_HEADER:\newcommand{\green}[1]{\textcolor{green}{#1}}
#+LATEX_HEADER:\newcommand{\orange}[1]{\textcolor{orange}{#1}}
#+latex_header: \usepackage[capitalise]{cleveref}

\def\udesoftecoverride#1\mainmatter{%
  \AfterEndPreamble{#1\mainmatter}

#+OPTIONS: toc:nil
#+OPTIONS: date:nil

#+OPTIONS: ':t
#+END_OPTIONS

#+Title: Characterization and Analysis of Ring Topology of Zeolite Frameworks

#+author:Jerry T. Crum^{a}, Justin R. Crum^{b}, Cameron Taylor^{a}, William F. Schneider^{a,c}
\maketitle

\begin{asparaenum}[\expandafter\textsuperscript a ]
\item Department of Chemical and Biolmolecular Engineering, University of Notre Dame, 250 Nieuwland Science Hall, Notre Dame, IN 46556, USA \\
\item Department of Applied Mathematics, University of Arizona, 617 N Santa Rita Ave, Tucson, AZ 85721, USA\\
\item Department of Chemistry and Biochemistry, University of Notre Dame, 251 Nieuwland Science Hall, Notre Dame, IN 46556, USA
\end{asparaenum}

\newpage
* Abstract
The topology of zeolite frameworks and of associated tetrahedral sites (T-sites) are commonly characterized by their associated rings, typically defined as some set of closed paths or cycles through a framework that cannot be decomposed into shorter cycles. These ring descriptors have been used to identify feasible zeolite topologies, to describe the similarity and differences between zeolites, to identify sites or voids of catalytic relevance, and as machine learning fingerprints. Numerous definitions and algorithms for finding zeolite rings have been proposed and applied throughout the literature. Here we report an analysis of rings and T-sites in a large number of zeolite frameworks using Zeolite Simulation Environment, a Python package that implements an efficient algorithm presented by Goetzke and Klein for finding rings in arbitrary frameworks. We compare the result of a number of common and new ring definitions applied to a large number of common zeolite frameworks. We discover previously unrecognized rings in a number of frameworks. We show that the vertex symbol, a common approach used to characterize T-sites, misses important parts of the stereochemistry around a T-site, and propose an alternative definition. This tool provides an effective platform for characterizing zeolite and T-site structures useful for building models and doing machine learning. 

   
* Highlights
What is the main point of the paper? What problem is it addressing? What are the main insights?

1. Zeolite framework and nodes commonly classified in terms of rings
2. Various conventions for associating some subsets of rings with either a framework, the T-sites of a framework, or the oxygens of a framework.
3. PROBLEM TO ADDRESS: The convention used will provide different ring counts
4. SOLUTION: We provide a Python package that has the ability to identify and classify these rings based on previously published and new conventions
5. This software tool uses a node-based search procedure that takes advantage of algorithms developed for general nets
6. We compute and compare conventions across all known frameworks, highlighting differences in which rings get counted by which convention
7. Some features treated by convention as rings are not rings in a topological sense but are rather defined by the void space they create.
8. We show that the common method of describing a T-site by it's vertex symbol does not incorporate important information about the stereochemistry of the rings, and provide a new method for listing vertex symbol rings that compensates for that deficiency

* Introduction

**Paragraph 1: background on uses for zeolite rings**
- Zeolites are microporous and crystalline, natural to characterize by the sizes of the features present in the crystal.  Rings are one common type of feature widely reported and used, both to characterize a zeolite crystal and as descriptors of the individual tetrahedral sites of the zeolite. 

- Rings have been used to identify feasible zeolite topologies cite:li-why-2014, to describe the similarity and differences between zeolites cite:curtis-statistical-2003, to identify sites or voids of catalytic relevance cite:li-first-principles-2018,kester-effects-2021, and as machine learning finger prints [will get citations for this]

**Paragraph 2: Explain features of graph representing zeolites**
- Zeolites can naturally be represented using graph theory, where atoms are nodes, and bonds are edges. \red{REFS}
  - Sometimes in the literature, oxygen atoms are used as bridges instead of nodes, since they only connect to two T-sites
- Cref:tab:ring-def summarizes the various topological features based on connectivity that can be used to describe a framework, T-site, or oxygen atom
- A path is a series of connected nodes from some source node to some target node
- A cycle is a path that starts and ends at the same node, and doesn't repeat any other nodes

**Paragraph 3: Explain the various ring counting methodologies we intend to cover**
- Rings in zeolites are defined as a cycle traversing the T-site and oxygen atoms (nodes) of the framework, and cannot be decomposed into smaller cycles by a shortcut cite:goetzke-properties-1991,guttman-ring-1990.
- A shortcut is defined as a path connecting two nodes of a cycle that is shorter than both the paths connecting those nodes along the cycle cite:goetzke-properties-1991,guttman-ring-1990
- Shortest path ring is a ring that is the shortest ring for at least one set of O-T-O on the cycle cite:sastre-topological-2009, this ring will be contained in the vertex symbol for at least one of the T-sites within the framework 
- See Cref:fig:cha-labeled for example of rings
  - The pink highlighted cycle (1-2-3-17-20-14-15-16) is a 8-membered ring (8-MR)
  - The green highlighted cycle (14-20-12-13) is a 4-MR
  - The red outlined cycle following 3-4-18-19-20-17 is not an 6-MR because there is a shortcut connecting nodes 17 and 18.
  - Nodes 5-6-7-8-9 outlined in teal represent a path through the framework. 

#+attr_latex: :float :width 0.60\textwidth
#+caption: Cutout of the Chabazite framework showing a path (5-6-7-8-9) highlighted with purple bonds, a cycle (3-4-18-19-20-17) highlighted with blue bonds, an 8-MR filled in with pink, and a 4-MR filled in with green. Yellow atoms are Si (T-sites), and red atoms are oxygen. label:fig:cha-labeled
file:../figures/completed-figures/ring-examples2.pdf

\newpage

#+CAPTION: Matrix showing relationship between frameoworks, nodes, paths, cycles, and various ring types. \red{Vertex symbol doesn't belong in the first column. It isn't a topological feature.} label:tab:ring-def
#+ATTR_LATEX: :environment longtable :align l p{2.7cm} p{2.7cm} p{2.7cm} p{2.7cm}
|                     | <40>                                                                                                              | <30>                                                                        | <30>                                                      |                                                           |
|                     | Description                                                                                                       | Framework                                                                   | Node (T-Sites)                                            | Node (Oxygen)                                             |
|---------------------+-------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------+-----------------------------------------------------------+-----------------------------------------------------------|
| Nodes               | T-sites and oxygen atoms                                                                                          | Contains some set of symmetry distinct T-sites and oxygen atoms             |                                                           |                                                           |
| Paths               | Collection of connected nodes from source to target                                                               | Periodic cell contains an infinite number of paths                          |                                                           |                                                           |
| Cycles              | Path that starts and ends at the same node                                                                        | Periodic cell contains an infinite number of cycles                         |                                                           |                                                           |
| Rings               | Cycle that contains no shortcuts                                                                                  | Contains a finite number of unique rings                                    | All rings that pass through particular T-site             | All rings that pass through particular oxygen atom        |
| Unstacked Rings     | Ring that does not traverse two stacked rings                                                                     | A subset of the Rings above                                                 | All unstacked rings that pass through T-site              | All unstacked rings that pass through oxygen atom         |
| Shortest Path Rings | Ring that is the shortest ring for at least one set of O-T-O on the cycle                                         | A smaller subset of the rings above                                         | All shortest path rings starting from a T-site (Vertex)   | All shortest path rings that pass through oxygen atom     |
| \red{Vertex Symbol} | Way to classify the rings around a T-site, shortest ring (and its multiplicity) for each O-O pair around a T-site | Collection of vertex symbols for all symmetry distinct T-sites in framework | Vertex symbol for particular T-site                       |                                                           |
| Geometric rings     | A cycle that may contain a shortcut, but has similar geometric/chemical properties to a ring without a shortcut   | Contains a finite number of geometric rings                                 | Can be described by the geometric rings that pass through | Can be described by the geometric rings that pass through |


**Paragraph 4: Problem to address**
- Different conventions exist that can reduce the set of rings to more strictly defined properties
- These methods return different sets of rings
- We can use rings to characterize oxygen atoms, T-sites, and entire frameworks
- T-sites:
  - Vertex symbols are the set of shortest paths connecting the 6 oxygen-oxygen pairs around a T-site cite:okeeffe-vertex-1997
  - Shortest path rings count all the vertex symbol rings that pass through a T-site or an oxygen atom cite:sastre-topological-2009
  - Or we can count all the rings that do not have a short cut cite:goetzke-properties-1991
- Oxygen atoms:
  - Shortest path rings
  - All rings with out a shortcut
- Framework
  - Vertex symbol rings
  - Shortest path rings
  - All rings with out a shortcut
- Differences in ring counts leads to differences in how we describe the topology of zeolites. Therefore, when discussing the rings in a zeolite it is important to also state which method of ring counting is used.

**Paragraph 5: Our solution to the problem**
- Here we present Zeolite Simulation Environment (ZSE), a Python package that implements the ring finding algorithm presented by Goetzke and Klein cite:goetzke-properties-1991 to find rings up to a user defined cutoff size, and can implement the previously published ring set reduction conventions.
- We use ZSE to provide an analysis of rings using each of these conventions on the entire set of IZA zeolite frameworks to compare how they result in different characterizations 

Using ZSE we show the differences in framework, T-site, and oxygen ring descriptors when using the various ring counting conventions. We highlight rings that are found by these conventions but not typically discussed for a number of frameworks. We also show that the vertex symbol, a common approach used to characterize T-sites misses important parts of the stereochemistry around a T-site. 


* Software Description

**Paragraph 1: Basics of ZSE tootls**
- All of the frameworks listed on the IZA Database of zeolite structures cite:baerlocher-database-nodate are included in a database with ZSE
- These structures are Atomic Simulation Environment Atoms objects cite:larsen-atomic-2017, and can be used with any of the functions in ZSE
- ZSE also includes CIF tools to read structure files for frameworks not listed in the IZA website, such as hypothetical zeolites, and return an Atoms object that can be used with ZSE

**Paragraph 2: Implementation of ring counting methodologies**
- ZSE has 3 previously published rules for ring finding implemented
  - All cycles without a shortcut cite:goetzke-properties-1991
  - All shortest path cycles cite:sastre-topological-2009
  - Cycles that compose the vertex symbol for a T-site cite:okeeffe-vertex-1997
- We have also implemented a new rule that finds all rings with out a shortcut, but excludes rings that are made by traversing a stacked set of rings. \red{Have to define stacked ring.}
  - Figure showing example of 8-MR in the d6r of CHA and 14-MR in AFI
- Each of the rules: shortest path, vertex symbols, and our new rule are a subset of the no shortcuts rule

**Paragraph 3: Process to find rings**

Process to find rings:
1. To find rings in a zeolite, ZSE makes a custom connectivity matrix for the Si and O atoms in the framework
2. We use NetworkX cite:hagberg-exploring-2008 to build a shortest path matrix for every atom pair in the zeolite framework
3. We then find all the rings up to some cutoff size base on the algorithm presented by Goetzke and Klein cite:goetzke-properties-1991
4. Depending on the rule chosen by the user, ZSE then removes rings from this list that don't meet the qualifications of the rule
5. ZSE returns a list of the rings found, a list of the atom indicies that compose each ring, Atoms objects for each ring that can be further analyzed or visualized by the user


* Results and Discussion
** Characterizing rings in a zeolite graph
**Paragraph 1: IZA doesn't list all rings in a framework**
- IZA is a common reference used to identify all the rings in a zeolite framework
- It only lists the rings that define a channel (ex: 12-MR in AFI), or rings associated with the vertex symbol of a T-site
- These rings have been called tabulated rings in previous literature cite:curtis-statistical-2003
- In some frameworks, other rings (cycles not containing shortcuts) exist that are not included in the tabulated rings
- These rings still may provide important information about the topology of a zeolite framework, or the local void environment around a T-site
- cref:fig:framework-counts shows counts of frameworks containing each size ring from 3- to 18-MR using the Goetzke algorithm and the listed rings on the IZA database
- At larger sized rings (>8-MR) we see the two counts diverge

#+attr_latex: :float :width .6\textwidth
#+caption: Counts of frameworks containing each size rings between 3 and 18-MR using the Goetzke algorithm and the tabulated rings on the IZA database. label:fig:framework-counts
file:../figures/completed-figures/rings-vs-iza-rings.pdf

**Paragraph 2: Example of untabulated rings in CHA shows 12-MR belt on cage, and 8-MRs in the D6R**
- Taking a closer look at some of these untabulated rings, highlights rings not typically but listed for some frameworks, but still relevant to describing their topology 
- Here we show an example of untabulated rings in the Chabazite framework
- Show the cage belts results for CHA, AFT, etc... and discuss how those rings don't show up in previous literature, Cref:fig:cha-rings
  - Looking at results for CHA in Cref:tab:ring-counts we see the Goetzke method finds 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{1}
  - This is different from the results in the Sastre paper cite:sastre-topological-2009, in that they only show 2 8-MRs and no 12-MRs
  - The extra 8-MRs result from cycles traversing nodes in both 6-MRs of the d6r
  - The 12-MR is a cycle that circumferences the CHA cage
#+attr_latex: :float :width 0.45\textwidth :placement {c}{0.5\textwidth}
#+caption: Chabazite cage and d6r with highlighted rings: 4-MR in green, 8-MR in pink, and 12-MR in purple. The 8-MR in the d6r and the 12-MR are rings not typically discussed in literature, Si atoms have been replaced with Al atoms to help identify those rings in the overall cage structure. label:fig:cha-rings
file:../figures/completed-figures/cha-all-rings.pdf

**Paragraph 3: Untabulated rings in AFI also reveals rings traversing a pair of stacked rings**
- AFI has one unique T-site
- According to the IZA it contains 4, 6, and 12-MRs
- When we search using the Goetzke algorithm, we also find that it contains 14-MRs that traverses two stacked 12-MRs shown in cref:fig:afi-14
- These types of rings may not be of interest depending on what you want to describe
- Using the method outlined in section X.Y we can remove these types of rings from the Goetzke ring counts
#+attr_latex: :float :width 0.45\textwidth :placement {c}{0.5\textwidth}
#+caption: 12-MR channel in AFI with a 14-MR traversing 7 T-sites of each 12-MR highlighted in purple. label:fig:afi-14
file:../figures/completed-figures/afi-14.pdf

** Characterizing frameworks by rings
**Paragraph 4: Comparing all 4 ringing finding conventions and IZA listed rings by counting the number of frameworks containing each size ring**
- Plot showing how many frameworks on the IZA contain each size ring found using the various ring counting methods
- This highlights the differences in the conventions, and shows that results will vary depending on method used.
- In general a hierarchy of rings sizes found by each method is rings>this work>shortest path rings>vertex symbol rings
- While the IZA lists all vertex symbol rings, and a selection of general rings
- \red{How many unique combinations of ring sizes within all known zeolites?}

#+attr_latex: :float :width .6\textwidth
#+caption: Number of IZA frameworks containing each size ring, using the various ring counting rules. [This will be updated with the Sastre method, vertex method, and the rings listed on  the IZA website. Currently the IZA does not show any ring data for the SVY framework, providing one less framework to count.  label:fig:ring-counts
file:../figures/completed-figures/ring-counts.pdf

**Paragraph 5: Some cycles behave like rings while not be considered rings by connectivity rules** 
- On the other end of the spectrum, there are cycles that would not be classified as a rings by the connectivity rules previously outlined, but display properties similar to rings
- The trade-off to using well defined connectivity based ring definitions leaves out these particular void environments that may still be of interest
- These shortcut containing cycles can display chemical and/or geometric properties consistent with rings, and are of interest to catalysis researchers even though they are not considered rings by connectivity rules
- One example is the 6-membered cycle referred to as the \alpha-6-MR in literature (Cref:fig:mfi-6) and is present in a number of frameworks including but not limited to  MOR, FER, MFI, and BEA cite:dedecek-siting-2012,bernauer-proton-2016, which is a potential location for Co^{2+} uptake when two Al atoms are 3rd nearest neighbor in the cycle. Similar to Co^{2+} uptake in 3NN Al atoms in 6-MRs in other frameworks such as CHA and AEI.
- This 6-membered cycle would not be considered a ring by any of the connectivity rules outlined here due to the shortcut splitting the cycle into two 5-MRs

#+attr_latex: :float :width .4\textwidth
#+caption: Cutout of MFI framework showing the structure referred to as an \alpha-6-MR in blue, and the two 5-MRs that compose it in green. The 6-membered cycle would not be found as a ring by any of the connectivity ring rules (Goetzke, Crum, Sastre, or vertex symbol). label:fig:mfi-6
file:../figures/completed-figures/MFI-6MC.pdf

** Characterizing T-sites by rings
Motivate this....

**Paragraph 6: We can describe T-sites of a framework by the rings of that framework that pass through it AFI Example**
- Take for example the AFI framework, made of 4, 6, 12, and 14-MRs and containing one symmetry distinct T-site
- We can describe that T-site by counting how many rings of each size pass through it 
- We can prune this list of rings using other definitions, such as the shortest path rings presented by Sastre et al. cite:sastre-topological-2009, by counting only the vertex symbol rings cite:okeeffe-vertex-1997, or by our new algorithm that removes any ring that traverses a stacked set of rings
- Listing these rings by using a ring index (size_{count} from smallest to largest rings) cite:sastre-topological-2009 shows the differences in counts by each method
  - Rings: 4\bullet6_{13}\bullet12\bullet14_{7}
  - This work: 4\bullet6_{13}\bullet12
  - Shortest Path Rings: 4\bullet6_{13}
  - Vertex Symbol Rings: 4\bullet6_{11}
- Each method returns a different count, this is highlighted in figure...
#+attr_latex: :float :width .6\textwidth
#+caption: Diagram showing the ring counts of each size ring that pass through the single symmetry distinct T-site in AFI for each of the various ring finding conventions. label:fig:afi-funnel
file:../figures/completed-figures/afi-funnel.pdf

**Paragraph 7: Comparison to previously published results by Sastre**
#+CAPTION: Comparison of Ring Indices for the T-sites in Various Uninodal Zeolite Frameworks label:tab:ring-counts
| Framework | Rings                                         | This Work                                  | Shortest Path Rings cite:sastre-topological-2009 | Vertex Symbol Rings cite:baerlocher-database-nodate  |
|-----------+-----------------------------------------------+--------------------------------------------+--------------------------------------------------+------------------------------------------------------|
| ABW       | 4_{2}\bullet6_{3}\bullet8_{4}                 | 4_{2}\bullet6_{3}\bullet8_{4}              | 4_{2}\bullet6_{3}\bullet8_{4}                    | 4_{2}\bullet6_{3}\bullet8_{2}                        |
| ACO       | 4_{3}\bullet6_{3}\bullet8_{6}\bullet10_{15}   | 4_{3}\bullet8_{6}                          | 4_{3}\bullet8_{6}                                | 4_{3}\bullet8_{6}                                    |
| AFI       | 4_{1}\bullet6_{13}\bullet12_{1}\bullet14_{7}  | 4_{1}\bullet6_{13}\bullet12_{1}            | 4_{1}\bullet6_{13}                               | 4_{1}\bullet6_{11}                                   |
| ANA       | 4_{2}\bullet6_{2}\bullet8_{16}                | 4_{2}\bullet6_{2}\bullet8_{16}             | 4_{2}\bullet6_{2}\bullet8_{16}                   | 4_{2}\bullet6_{2}\bullet8_{8}                        |
| ATO       | 4_{1}\bullet6_{9}\bullet8_{8}\bullet12_{20}   | 4_{1}\bullet6_{9}\bullet12_{20}            | 4_{1}\bullet6_{9}                                | 4_{1}\bullet6_{9}                                    |
| BCT       | 4_{1}\bullet6_{6}\bullet8_{20}                | 4_{1}\bullet6_{6}\bullet8_{12}             | 4_{1}\bullet6_{6}                                | 4_{1}\bullet6_{6}                                    |
| CHA       | 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{1}    | 4_{3}\bullet6_{1}\bullet8_{2}\bullet12_{1} | 4_{3}\bullet6_{1}\bullet8_{2}                    | 4_{3}\bullet6_{1}\bullet8_{2}                        |
| DFT       | 4_{2}\bullet6_{6}\bullet8_{10}\bullet10_{10}  | 4_{2}\bullet6_{6}\bullet8_{10}             | 4_{2}\bullet6_{6}\bullet8_{10}                   | 4_{2}\bullet6_{4}\bullet8_{6}                        |
| GIS       | 4_{3}\bullet8_{4}                             | 4_{3}\bullet8_{4}                          | 4_{3}\bullet8_{4}                                | 4_{3}\bullet8_{4}                                    |
| GME       | 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{7}    | 4_{3}\bullet6_{1}\bullet8_{2}\bullet12_{1} | 4_{3}\bullet6_{1}\bullet8_{2}                    | 4_{3}\bullet6_{1}\bullet8_{2}                        |
| MER       | 4_{3}\bullet8_{4}\bullet10_{10}\bullet14_{14} | 4_{3}\bullet8_{4}                          | 4_{3}\bullet8_{4}                                | 4_{3}\bullet8_{4}                                    |
| MON       | 4_{1}\bullet5_{5}\bullet8_{6}                 | 4_{1}\bullet5_{5}\bullet8_{6}              | 4_{1}\bullet5_{5}\bullet8_{6}                    | 4_{1}\bullet5_{4}\bullet8_{4}                        |
| NPO       | 3_{1}\bullet6_{6}\bullet12_{40}               | 3_{1}\bullet6_{6}\bullet12_{40}            | 3_{1}\bullet6_{6}                                | 3_{1}\bullet6_{6}                                    |


- Reproduce the results from Sastre paper, show ring counts with the other rules, Cref:tab:ring-counts
  - Results in the Sastre column were found using ZSE but agree directly with the results shown by Sastre and Corma cite:sastre-topological-2009
  - Results in the Vertex symbol rings column were also found with ZSE but agree directly will the vertex symbols listed on the IZA website
    - These vertex symbols have been compressed into a ring index to compare with the other methods 
  - This provides an in depth look at some of the frameworks and the differences in rings found by each rule.
  - Leads into the next section discussing the specific rings of CHA and pentasil that do or don't get counted by each rule.


**Paragraph 8: Example of T-site ring counts for 6 symmetry distinct T-sites in MOZ shows limitations of shortest path and vertex symbol rings**
- MOZ framework is made of 4, 6, 8, 10, 12, 14, and 18-MRs, and contains 6 symmetry distinct T-sites
- cref:table:moz shows the ring index for each T-site using each ring finding method
#+caption: Ring indices for each distinct T-site in the MOZ framework using each ring counting convention. label:table:moz
| T-Site | Rings                                  | This Work                   | Shortest Path Rings     | Vertex Symbol Rings     |
|--------+----------------------------------------+-----------------------------+-------------------------+-------------------------|
| T1     | 4_{3}•6_{2}•8_{7}•10_{7}•18_{5}        | 4_{3}•6_{2}•8_{3}           | 4_{3}•6_{2}•8_{3}       | 4_{3}•6_{2}•8           |
| T2     | 4_{3}•6_{2}•8_{7}•10_{7}•14_{5}        | 4_{3}•6_{2}•8_{3}           | 4_{3}•6_{2}•8_{3}       | 4_{3}•6_{2}•8           |
| T3     | 4_{3}•6_{2}•8_{5}•10_{4}•12_{4}•14_{5} | 4_{3}•6_{2}•8•12_{4}        | 4_{3}•6_{2}•8           | 4_{3}•6_{2}•8           |
| T4     | 4_{2}•6•8_{6}•10_{6}•12•18_{26}        | 4_{2}•6•8_{6}•12            | 4_{2}•6•8_{6}•12        | 4_{2}•6•8_{6}•12        |
| T5     | 4_{2}•6•8_{7}•10_{6}•14_{18}           | 4_{2}•6•8_{7}               | 4_{2}•6•8_{7}           | 4_{2}•6•8_{7}           |
| T6     | 4_{2}•6•8_{3}•10_{2}•12_{8}•14_{18}    | 4_{2}•6•8_{3}•12_{8}        | 4_{2}•6•8_{3}           | 4_{2}•6•8_{3}           |

- cref:fig:moz shows the T-site locations inside the framework
- If you were interested in which T-sites have access to the 12-MR channels, the shortest path rings and vertex symbol rings would only say T3
- However general rings, and this work would tell you T4 and T6 also have access to the 12-MR channels as highlighted in Figure ..
#+attr_latex: :float :width .5\textwidth
#+caption: Cutout of the MOZ framework showing two 12-MR channels, with distinct T-sites highlighted. T1: navy, T2: green, T3: orange, T4: purple, T5: blue, T6: red. label:fig:moz
file:../figures/completed-figures/moz.pdf

**Paragraph 9: Comparing ring counts for every T-site across the IZA database highlights differences in conventions**
- Number of unique T-sites
  - There are 1460 T-sites through all the frameworks listed on the IZA website.
  - We can characterize those T-sites by the rings that pass through them
  - Most common T-site ring index using Goetzke method is: 5_{6}\bullet10_{4} showing up 23 times through the IZA frameworks.
  - Most common T-site ring index using Crum method is: 4_{3}\bullet8_{4} showing up 31 times through the IZA frameworks.
    - Next most common T-site with Crum method is 5_{6}\bullet10_{4} showing up 25 times
  - This raises the question, if you want to ascertain chemical or physical properties about a T-site based on it's ring count, the results will depend on the convention used
#+attr_latex: :float :width .6\textwidth
#+caption: Number of unique T-sites when classified by the rings passing through them using varrious ring finding rules. label:fig:unique-ts
file:../figures/completed-figures/unique-ts.pdf

#+attr_latex: :float :width .8\textwidth
#+caption: Frequency of T-sites across all IZA frameworks containing ring sizes between 3- and 18-MR (left), and cumulative distribution of T-sites containing each ring size normalized to final rings value (right). label:fig:tsite-frequency
file:../figures/completed-figures/dist-cumudist.pdf

**Paragraph 10: Similarity of results returned by each ring finding convention**
- Here we use a similarity score to determine how similar or different the rings found by each counting method are to each other
- The similarity score is determined by cref:eq:similarity, where $sr$ is the number of similar rings found by each method, and $mr$ is the max number of rings found by either method. 
\begin{equation}\label{eq:similarity}
s = \frac{sr}{mr}
\end{equation}
- We compare each method for every T-site in the IZA database, and average the similarity scores for each method pair
- The results are shown in the following heat map
- We see that down the diagonal is each method compared to itself, and thus has a similarity score of 1
- The remainder of the table follows intuition 
- the most restrictive counting method (vertex symbol rings) compared to the least restrictive method (rings) has the lowest similarity score
- The two most similar ring counting methods are this work compared to the shortest path rings

#+attr_latex: :float :width .6\textwidth
#+caption: Heat map showing the similarity score for four ring counting methods. Similarity score of 1 means identical, and a similarity score of zero implies no similar rings found. label:fig:similarity
file:../figures/completed-figures/similarity-heat-map.pdf

**Paragraph 11: Stereochemistry concerns when using vertex symbols**
- Vertex symbols are common way to identify similar T-sites in zeolite frameworks
- The vertex symbol as defined lists the rings included by finding pairs of opposite edge rings, and listing them from smallest pair to largest pair
- This method does not capture subtle but distinct differences in the orientation of the rings around the T-site that can lead to varying local void environments
- For example: MOR T3, MON T1, and EON T9 all have the same vertex symbol of: 4\bullet5_{2}\bullet5\bullet8_{2}\bullet5\bullet8_{2}
  - So each T-site is a member of one 4-MR, four 5-MRs, and four 8-MRs
  - However, the orientation of those rings around each of those T-sites are not identical
  - FIGURE below shows a cutout of each of these frameworks only including the atoms that make up the vertex symbol rings around the specified T-sites 
  - We can see that MOR T3 and EON T9 have the same ring orientation, and that orientation is different from the rings making up MON T1
  - \red{I can make this figure better with more angles, and maybe include a line diagram explaining the differences}

#+attr_latex: :float :width .6\textwidth
#+caption: Cutout of MOR, EON, and MON that only shows the rings associated with the vertex symbol of T3, T9, and T1 respectively. label:fig:stereo
file:../figures/completed-figures/stereo.png

- This has lead us to create a new method for listing the rings in the vertex symbol that takes into account the structural connection of the rings
  - This is accomplished by assigning a weight to each of the oxygen atoms around the T-site in question based on the size of rings that connect to that oxygen
  - \red{need to work out how to describe the method here}
  - With this new descriptor MOR T3 and EON T9 would be labeled as: 8_{2}\bullet8_{2}\bullet5_{2}\bullet5\bullet4\bullet5 and MON T1 as: 8_{2}\bullet8_{2}\bullet4\bullet5\bullet5_{2}\bullet5
  - The difference is subtle, but highlights the distinct structural  difference between the two types of T-sites that is not otherwise captured by a vertex symbol
- \red{Here we would include a table of some of the most common vertex symbols, and how many different variations they have with this new descriptor}

- Stereochemistry of the rings associated with a T-site could influence the chemical properties we care about, such as deprotonation energy, T-site substitution energy, or catalytic properties
- This would indicate that a vertex symbol is not a complete descriptor, and there is room to define a new descriptor that takes into consideration ring orientation.

**Everything below here is not intended to be included in the main text of the paper**

**Paragraph 3: Differences in O-sites**
- Number of unique oxygen sites
  - We can repeat this method for the oxygen atoms in all the frameworks
  - Counting the symmetry distinct oxygen atoms in each framework on the IZA database leads to a total count of 3219
  - We can classify those oxygen atoms based on the rings that pass through them, using the various ring counting rules
  - Cref:fig:unique-os shows counts based on ring finding rules
  - The percentage of unique oxygen sites is much lower than the percentage of unique T-sites for every ring finding method 

#+attr_latex: :float :width .6\textwidth
#+caption: Number of unique oxygen sites when classified by the rings passing through them using varrious ring finding rules. Vertex method not included, since that is a way to classify T-sites only. label:fig:unique-os
file:../figures/completed-figures/unique-os.pdf

Note that in Cref:fig:osite-frequency a bar for Vertex rings is not present. This is because the Vertex symbol only defines rings that pass through a specific T-site. 

#+attr_latex: :float :width .6\textwidth
#+caption: Frequency of O-sites across all IZA frameworks containing ring sizes between 3- and 18-MR. label:fig:osite-frequency
file:../figures/completed-figures/osite-ring-counts.pdf
- Here we show the most common ring indices for T-sites in the IZA database using each of the ring finding rules
- Cref:tab:goetzke-ts shows the five most common ring indices for T-sites using the Goetzke  rule
#+CAPTION: Most Common Ring Indices Using the Goetzke Rule label:tab:goetzke-ts
| Ring Index                                              | Count | Frameworks Containing Index     |
|---------------------------------------------------------+-------+---------------------------------|
| 5_{6}\bullet10_{4}                                      |    23 | IMF(2), MEL(1), MFI(2), PRO(1), |
|                                                         |       | SVR(2), TUN(2), SFV(13)         |
| 4_{1}\bullet5_{3}\bullet6_{2}\bullet10_{3}\bullet12_{4} |    14 | MEL(1), SFV(13)                 |
| 4_{1}\bullet5_{3}\bullet6_{2}\bullet8_{5}\bullet10_{1}  |    14 | MEL(1), SFV(13)                 |
| 5_{5}\bullet6_{3}\bullet10_{1}\bullet12_{1}             |    14 | MEL(1), SFV(13)                 |
| 5_{4}\bullet6_{3}\bullet8_{2}\bullet10_{3}              |    14 | MEL(1), SFV(13)                 |

\newpage
- Cref:tab:crum-ts shows the five most common ring indices for T-sites using the Crum rule
#+CAPTION: Five Most Common Ring Indices Using the Crum Rule label:tab:crum-ts
| Ring Index                                 | Count | Frameworks Containing Index      |
|--------------------------------------------+-------+----------------------------------|
| 4_{3}\bullet8_{4}                          |    31 | APC(1), GIS(1), MER(1), MWF(13), |
|                                            |       | PAU(6), PHI(2), PWN(2), SIV(4)   |
| 5_{6}\bullet10_{4}                         |    25 | IMF(3), MEL(1), MFI(2), RRO(1),  |
|                                            |       | SVR(2), TUN(3), SFV(13)          |
| 4_{2}\bullet6_{4}                          |    17 | FAR(1), FRA(6), GIU(1), LIO(1),  |
|                                            |       | LOS(2), LTN(2), MAR(1), SOD(1),  |
|                                            |       | TOL(2)                           |
| 5_{5}\bullet6_{3}\bullet10_{1}             |    17 | IMF(1), MEL(1), MFI(1), TUN(1),  |
|                                            |       | SFV(13)                          |
| 4_{3}\bullet6_{1}\bullet8_{2}\bullet12_{1} |    16 | AFS(1), AFT(3), AFV(1), AFX(2),  |
|                                            |       | AVL(2), BPH(1), CHA(1), GME(1),  |
|                                            |       | SBE(1), SFW(3)                   |

- Cref:tab:sastre-ts shows the five most common ring indices for T-sites using the Sastre rule
#+CAPTION: Five Most Common Ring Indices Using the Sastre Rule label:tab:sastre-ts
| Ring Index                    | Count | Frameworks Containing Index      |
|-------------------------------+-------+----------------------------------|
| 4_{2}\bullet6_{4}             |    39 | AFG(3), CAN(1), FAR(4), FRA(6),  |
|                               |       | GIU(5), LIO(4), LOS(2), LTN(2)   |
|                               |       | MAR(4), SOD(1), TOL(7)           |
| 5_{6}\bullet10_{4}            |    33 | IMF(3), MEL(2), MFI(2), RRO(1),  |
|                               |       | SVR(2), TUN(2), SFV(21)          |
| 4_{3}\bullet8_{4}             |    30 | GIS(1), MER(1), MWF(14), PAU(6), |
|                               |       | PHI(2), PWN(2), SIV(4)           |
| 4_{3}\bullet6_{1}\bullet8_{2} |    28 | AEI(3), AFT(3), AFV(1), AFX(2),  |
|                               |       | AVL(2), CHA(1), GME(1), KFI(1),  |
|                               |       | LTF(1), MWF(2), PAU(2), PWN(1),  |
|                               |       | RHO(1), SAV(3), SFW(3), TSC(1)   |
| 4_{3}\bullet6_{2}\bullet8_{1} |    24 | AFV(1), AVE(2), AVL(1), CLO(2),  |
|                               |       | EAB(1), ERI(1), IFY(1), IRN(1),  |
|                               |       | LEV(1), LTA(1), LTN(1), MOZ(1),  |
|                               |       | OFF(1), SAT(1), SWY(2), TSC(1),  |
|                               |       | UFI(1), PTT(1), SYT(3)           |

- Cref:tab:vertex-ts shows the five most common ring indices for T-sites using vertex symbols
#+CAPTION: Five Most Common Ring Indices Using Vertex Symbolscite:bernauer-proton-2016 label:tab:vertex-ts
| Vertex Symbol                                 | Count | Frameworks Containing Index      |
|-----------------------------------------------+-------+----------------------------------|
| 4\bullet4\bullet6\bullet6\bullet6\bullet6     |    40 | AFG(3), CAN(1), FAR(4), FRA(6),  |
|                                               |       | GIU(5), LIO(4), LOS(2), LTN(2),  |
|                                               |       | MAR(4), RON(1), SOD(1), TOL(7)   |
| 4\bullet4\bullet4\bullet6\bullet8\bullet8     |    32 | AEI(3), AFT(3), AFV(1), AFX(2),  |
|                                               |       | ATT(1), AVL(2), CHA(1), ETV(1),  |
|                                               |       | GME(1), KFI(1), LTF(1), MRT(2),  |
|                                               |       | MWF(2), PAU(2), PWN(1), RHO(1),  |
|                                               |       | SAV(3), SFW(3), TSC(1)           |
| 4\bullet4\bullet4\bullet6\bullet6\bullet8     |    30 | AFV(1), AVE(2), AVL(1), CGS(1),  |
|                                               |       | CLO(2), EAB(1), ERI(1), ETR(1),  |
|                                               |       | IFY(1), IRN(1), JSW(1), LEV(1),  |
|                                               |       | LTA(1), LTL(1), LTN(1), MOZ(3),  |
|                                               |       | OFF(1), PTT(1), SAT(1), SWY(2),  |
|                                               |       | SYT(3), TSC(1), UFI(1)           |
| 4\bullet4\bullet4\bullet8\bullet8\bullet8_{2} |    30 | GIS(1), MER(1), MWF(14), PAU(6), |
|                                               |       | PHI(2), PWN(2), SIV(4)           |
| 5\bullet5\bullet5\bullet5\bullet5\bullet6     |    26 | DDR(1), DOH(2), IHW(1), IMF(1),  |
|                                               |       | MEL(1), MEP(1), MFI(1), MTN(1),  |
|                                               |       | SFS(1), SFV(15), TUN(1)          |

\newpage
\red{Removed paragraph, because we don't want to describe frameworks using these other ring finding methods. Keeping text in case we want to bring this back.}
**Paragraph 1: Differences in frameworks**


* Conclusions---Needs to be updated
- \red{Conclusions need to be connected to motivations and results above. Should connect to points made in abstract. Why do I care about rings in a framework? What are their practical significance?}

- \red{Rings of graph are well defined; here identify all rings up to XXX in YYY frameworks. Find that commonly reported (IZA) ring sizes miss certain rings.}

- Can characterize Fws by 


- The method used to find rings in a zeolite will provide different ring counts \red{unclear}
- When discussing rings in a zeolite it is import to disclose by which method those rings were found
- Using ZSE we can find rings based on various methods
- This provides a foundation for using ring fingerprints in machine learning models to correlate chemical properties and topology


bibliographystyle:unsrtnat
bibliography:ref.bib

* Acknowledgments 
- Funding
  - CISTAR
  - Schmitt Fellowship
- Discussions
  - Christian Baerlocher
- Software:
  - German Sastre: zeoTsites
- Compute Resources
  - CRC
