#+BEGIN_OPTIONS
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in,top=.75in,bottom=.75in}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{color}
#+LATEX_HEADER:\usepackage[numbers,super,sort&compress]{natbib}
#+LATEX_HEADER:\usepackage{caption}
#+LATEX_HEADER:\usepackage{subcaption}
#+LATEX_HEADER:\captionsetup{font=footnotesize}
#+LATEX_HEADER:\usepackage[version=3]{mhchem}
#+LATEX_HEADER:\usepackage{siunitx}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{paralist}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{enumitem}
#+LATEX_HEADER:\usepackage{mdwlist}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\usepackage{wrapfig}
#+LATEX_HEADER:\usepackage{nopageno}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\fancyhead[LE,RO]{\scriptsize Jerry Crum}
#+LATEX_HEADER:\fancyhead[RE,LO]{\scriptsize ZSE Outline}
#+LATEX_HEADER:%\fancyfoot[CE,CO]{\leftmark}
#+LATEX_HEADER:\fancyfoot[LE,RO]{\thepage}
#+LATEX_HEADER:%\usepackage{subfig}
#+LATEX_HEADER:\usepackage{comment}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[section]{placeins}
#+LATEX_HEADER: \usepackage{siunitx}

#+LATEX_HEADER:\DeclareGraphicsExtensions{.pdf,.png,.jpg}
#+LATEX_HEADER:\newcommand{\red}[1]{\textcolor{red}{#1}}
#+LATEX_HEADER:\newcommand{\blue}[1]{\textcolor{blue}{#1}}
#+LATEX_HEADER:\newcommand{\green}[1]{\textcolor{green}{#1}}
#+LATEX_HEADER:\newcommand{\orange}[1]{\textcolor{orange}{#1}}
#+latex_header: \usepackage[capitalise]{cleveref}

\def\udesoftecoverride#1\mainmatter{%
  \AfterEndPreamble{#1\mainmatter}

#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: H:3 num:nil
#+OPTIONS: ':t
#+END_OPTIONS

#+Title: ZSE Manuscript Outline

#+author:Jerry T. Crum^{a}, Justin R. Crum^{b}, William F. Schneider^{a,c}
\maketitle

\begin{asparaenum}[\expandafter\textsuperscript a ]
\item Department of Chemical and Biolmolecular Engineering, University of Notre Dame, 250 Nieuwland Science Hall, Notre Dame, IN 46556, USA \\
\item Department of Applied Mathematics, University of Arizona, 617 N Santa Rita Ave, Tucson, AZ 85721, USA\\
\item Department of Chemistry and Biochmeistry, University of Notre Dame, 251 Nieuwland Science Hall, Notre Dame, IN 46556, USA
\end{asparaenum}

\newpage
* Introduction
- Topology of zeolite frameworks and associated tetrahedral sites (T-sites) are commonly characterized by their associated rings
- Rings are defined as a close cycle traversing the T-site and oxygen atoms of the framework, and cannot be decomposed into smaller cycles by a shortcut cite:goetzke-properties-1991.
- A shortcut is defined as a path connecting two nodes of a cycle that is shorter than both the paths connecting those nodes along the cycle. 
- See Cref:fig:cha-labeled for example of rings
  - The blue highlighted cycle (8-3-4-5-6-7) is a 6-membered ring (6-MR)
  - The green highlighted cycle (1-2-3-8) is a 4-MR
  - The cycle following 1-2-3-4-5-6-7-8 is not an 8-MR because there is a shortcut connecting nodes 3 and 8. 

#+attr_latex: :float :width 0.60\textwidth
#+caption: Cutout of the Chabazite framework showing a 6-MR in blue and a 4-MR in green. Yellow atoms are Si (T-sites), and red atoms are oxygen. label:fig:cha-labeled
file:../figures/completed-figures/cha-labeled.pdf

- Rings have been used to identify feasible zeolite topologies cite:li-why-2014, to descirbe the similarity and differences between zeolites cite:curtis-statistical-2003, to identify sites or voids of catalytic relevance cite:li-first-principles-2018,kester-effects-2021, and as machine learning finger prints [will get citations for this]

- Different methods exist to count rings present in a zeolite
- These methods return different sets of rings
- Vertex symbols are the set of shortest paths connecting the 6 oxygen-oxygen pairs around a T-site cite:okeeffe-vertex-1997
- Shortest path rings count all the vertex symbol rings that pass through a T-site or an oxygen atom cite:sastre-topological-2009
- Or we can count all the rings that do not have a short cut cite:goetzke-properties-1991
- Differences in ring counts leads to differences in how we describe the topology of zeolites. Therefore, when discussing the rings in a zeolite it is important to also state which method of ring counting is used.
- Here we report an analysis of rings and T-sites in a large number of zeolite frameworks using Zeolite Simulation Environment, a Python package that implements an efficient algorithm presented by Goetzke and Klein cite:goetzke-properties-1991 for finding rings in arbitrary frameworks.
- We compare the results of a number of common and new ring definitions applied to a large number of common zeolite frameworks.cite:li-first-principles-2018

* Software Description

- All of the frameworks listed on the IZA Database of zeolite structures cite:IZA are included in a database with ZSE
- These structures are Atomic Simulation Environment Atoms objects cite:larsen-atomic-2017, and can be used with any of the functions in ZSE
- ZSE also includes CIF tools to read structure files for frameworks not listed in the IZA website, such as hypothetical zeolites, and return an Atoms object that can be used with ZSE
- ZSE has 3 previously published rules for ring finding implemented
  - All cycles with out a shortcut cite:goetzke-properties-1991
  - All shortest path cycles cite:sastre-topological-2009
  - Cycles that compose the vertex symbol for a T-site cite:okeeffe-vertex-1997
- We have also implemented a new rule that finds all rings with out a shortcut, but excludes rings that are made by traversing a stacked set of rings.
  - Figure showing example of 8-MR in the d6r of CHA and 14-MR in AFI
- Each of the rules: shortest path, vertex symbols, and our new rule are a subset of the no shortcuts rule
Process to find rings:
1. To find rings in a zeolite, ZSE makes a custom connectivity matrix for the Si and O atoms in the framework
2. We use NetworkX cite:SciPyProceedings-11 to build a shortest path matrix for every atom pair in the zeolite framework
3. We then find all the rings up to some cutoff size base on the algorithm presented by Goetzke and Klein cite:goetzke-properties-1991
4. Depending on the rule chosen by the user, ZSE then removes rings from this list that don't meet the qualifications of the rule
5. ZSE returns a list of the rings found, a list of the atom indicies that compose each ring, Atoms objects for each ring that can be further analyzed or visualized by the user


* Results
- Ring counts frequency plots
  - Plot showing how many frameworks on the IZA contain each size ring found using the various ring counting methods
  - This highlights the differences in the ring rules, and shows that results will vary depending on rule.
#+attr_latex: :float :width .6\textwidth
#+caption: Number of IZA frameworks containing each size ring, using the various ring counting rules. [This will be updated with the Sastre method, vertex method, and the rings listed on  the IZA website] label:fig:ring-counts
file:../figures/completed-figures/ring-counts.pdf

- Number of unique T-sites
  - There are 1460 T-sites through all the frameworks listed on the IZA website.
  - We can characterize those T-sites by the rings that pass through them
  - Sastre did this, and called the list of rings, the ring index
  - If we do this using different rules for ring finding how do the results change?
    - See Cref:fig:unique-ts
  - Most common T-site ring index using Goetzke method is: 5_{6}\bullet10_{4} showing up 23 times through the IZA frameworks.
  - Most common T-site ring index using Crum method is: 4_{3}\bullet8_{4} showing up 31 times through the IZA frameworks.
    - Next most common T-site with Crum method is 5_{6}\bullet10_{4} showing up 25 times
  - This raises the question, if you want to use machine learning to correlate T-site rings to chemical properties, which ring method should you use? 
#+attr_latex: :float :width .6\textwidth
#+caption: Number of unique T-sites when classified by the rings passing through them using varrious ring finding rules. [Sastre and Vertex method to be updated, still collecting data] label:fig:unique-ts
file:../figures/completed-figures/unique-ts.pdf

- Number of unique oxygen sites
  - We can repeat this method for the oxygen atoms in all the frameworks
  - There are 3219 oxygen atoms through all the frameworks listed on the IZA website
  - Figure here showing counts based on ring finding rules

- Reproduce the results from Sastre paper, show ring counts with the other rules, Cref:tab:ring-counts
  - Results in the Sastre column were found using ZSE but agree directly with the results shown by Sastre and Corma cite:sastre-topological-2009
  - This provides an in depth look at some of the frameworks and the differences in rings found by each rule.
  - Leads into the next section discussing the specific rings of CHA and pentasil that do or don't get counted by each rule.

#+CAPTION: Comparison of Ring Indices for the T-sites in Various Uninodal Zeolite Frameworks label:tab:ring-counts
| Framework | Goetzke                                       | Crum                                       | Sastre cite:sastre-topological-2009 |
|-----------+-----------------------------------------------+--------------------------------------------+-------------------------------------|
| ABW       | 4_{2}\bullet6_{3}\bullet8_{4}                 | 4_{2}\bullet6_{3}\bullet8_{4}              | 4_{2}\bullet6_{3}\bullet8_{4}       |
| ACO       | 4_{3}\bullet6_{3}\bullet8_{6}\bullet10_{15}   | 4_{3}\bullet8_{6}                          | 4_{3}\bullet8_{6}                   |
| AFI       | 4_{1}\bullet6_{13}\bullet12_{1}\bullet14_{7}  | 4_{1}\bullet6_{13}\bullet12_{1}            | 4_{1}\bullet6_{13}                  |
| ANA       | 4_{2}\bullet6_{2}\bullet8_{16}                | 4_{2}\bullet6_{2}\bullet8_{16}             | 4_{2}\bullet6_{2}\bullet8_{16}      |
| ATO       | 4_{1}\bullet6_{9}\bullet8_{8}\bullet12_{20}   | 4_{1}\bullet6_{9}\bullet12_{20}            | 4_{1}\bullet6_{9}                   |
| BCT       | 4_{1}\bullet6_{6}\bullet8_{20}                | 4_{1}\bullet6_{6}\bullet8_{12}             | 4_{1}\bullet6_{6}                   |
| CHA       | 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{1}    | 4_{3}\bullet6_{1}\bullet8_{2}\bullet12_{1} | 4_{3}\bullet6_{1}\bullet8_{2}       |
| DFT       | 4_{2}\bullet6_{6}\bullet8_{10}\bullet10_{10}  | 4_{2}\bullet6_{6}\bullet8_{10}             | 4_{2}\bullet6_{6}\bullet8_{10}      |
| GIS       | 4_{3}\bullet8_{4}                             | 4_{3}\bullet8_{4}                          | 4_{3}\bullet8_{4}                   |
| GME       | 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{7}    | 4_{3}\bullet6_{1}\bullet8_{2}\bullet12_{1} | 4_{3}\bullet6_{1}\bullet8_{2}       |
| MER       | 4_{3}\bullet8_{4}\bullet10_{10}\bullet14_{14} | 4_{3}\bullet8_{4}                          | 4_{3}\bullet8_{4}                   |
| MON       | 4_{1}\bullet5_{5}\bullet8_{6}                 | 4_{1}\bullet5_{5}\bullet8_{6}              | 4_{1}\bullet5_{5}\bullet8_{6}       |
| NPO       | 3_{1}\bullet6_{6}\bullet12_{40}               | 3_{1}\bullet6_{6}\bullet12_{40}            | 3_{1}\bullet6_{6}                   |

- Show the cage belts results for CHA, AFT, etc... and discuss how those rings don't show up in previous literature, Cref:fig:cha-rings
  - Looking at results from CHA we see the Goetzke method finds 4_{3}\bullet6_{1}\bullet8_{6}\bullet12_{1}
  - This is different from the results in the Sastre paper cite:sastre-topological-2009, in that they only show 2 8-MRs and no 12-MRs
  - The extra 8-MRs result from cycles traversing nodes in both 6-MRs of the d6r
  - The 12-MR is a cycle that circumferences the CHA cage
#+attr_latex: :float :width 0.45\textwidth :placement {c}{0.5\textwidth}
#+caption: Chabazite framework with highlighted rings: 4-MR in green, 6-MR in blue, 8-MR in pink, 12-MR in purple. The 8-MR in the d6r and the 12-MR are rings not typically discussed in literature. This is a placeholder figure, I want to show the rings in CHA for discussion. Hoping to get your input on how best to do that. label:fig:cha-rings
file:../figures/completed-figures/cha-all-rings.pdf

- Show the pentasil 6-membered cycle (MFI) and discuss how that is often considered a ring by catalysis researchers, but not a ring by the Goetzke definition

* Conclusions

- The method used to find rings in a zeolite will provide different ring counts
- When discussing rings in a zeolite it is import to disclose by which method those rings were found
- Using ZSE we can find rings based on various methods
- This provides a foundation for using ring fingerprints in machine learning models to correlate chemical properties and topology


bibliographystyle:unsrtnat
bibliography:ref.bib

